p8105_hw2_am4656
================
Aaron Mittel
2022-10-04

# Problem 1

*Imported “NYC_Transit_and_Subway_Entrance_and_Exit_Data.csv” from a
relative file path to my working directory, cleaned column names, and
then selected for only “line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance” by selecting for the range of columns incorporating those
variables and removing unwanted variables. Then, converted the entry
variable from character (YES vs NO) to a logical variable using
“ifelse”.*

Following these procedures, this dataset is now organized into **19
columns and 1868 rows**. The dataset contains variables describing
individual tracks/lines of the New York city subway transit system by
the associated street (e.g. 4th Avenue) that the track/line runs along,
stations along each track/line, individual trains/routes (e.g. A, B, C,
or D) that run on each track/line, geographic positions of each station,
and basic features of each station (whether a vending machine is
present, stairs or elevator used for access, whether the station is ADA
compliant).

The data is tidier than it once was. However, it does have some
redundancy and can be improved. Route \# should be a variable and route
should also be a variable (done below).

*We can select for unique combinations of station name, line, and ADA
accesability using the “distinct” function”.*

-   There are **465** distinct stations.

-   There are **84** distinct stations that are ADA compliant.

*We can compute the proportion of station entrances without vending that
allow entrance by first excluding station entrances that do not allow
vending. Then, we can take the mean of the entry variable (which will
produce the desired proportion because R will coerce logical to numeric
in cases like this).*

-   The proportion of station entrances without vending that allow
    entrance is thus **0.3770492**.

*We can identify distinct stations that serve the A train and are ADA
compliant by tidying the data to convert `route` from wide to long
format and filtering to focus on the A train.*

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

Thus, there are only **17** stations that serve the A train that are ADA
compliant.

## Problem 2

*Reading Mr. Trash Wheel into the R Project, the self-named first sheet
in the Excel file. We must skip the first row (which is just an image in
the original Excel file) and the last row (which appears to be summed
column values) to omit rows that do not include dumpster-specific data.
Variable names are largely reasonable, though we must add a variable to
distinguish this data from the additional Professor Trash Wheel data
that will be added in the next step. We convert the `sports_balls`
variable to an integer and also change the `year` variable to numeric
type, instead of character, so that it may be joined with Professor
Trash Wheel.*

*Reading Professor Trash Wheel into the R Project in a comparable manner
as above.*

*Stacking Mr. Trash Wheel and Professor Trash Wheel and relocating the
`wheel` and `dumpster` variables to the left side of the dataset for
easy viewing.*

    ## # A tibble: 641 × 15
    ##    wheel dumps…¹ month  year date                weigh…² volum…³ plast…⁴ polys…⁵
    ##    <chr>   <dbl> <chr> <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 mist…       1 May    2014 2014-05-16 00:00:00    4.31      18    1450    1820
    ##  2 mist…       2 May    2014 2014-05-16 00:00:00    2.74      13    1120    1030
    ##  3 mist…       3 May    2014 2014-05-16 00:00:00    3.45      15    2450    3100
    ##  4 mist…       4 May    2014 2014-05-17 00:00:00    3.1       15    2380    2730
    ##  5 mist…       5 May    2014 2014-05-17 00:00:00    4.06      18     980     870
    ##  6 mist…       6 May    2014 2014-05-20 00:00:00    2.71      13    1430    2140
    ##  7 mist…       7 May    2014 2014-05-21 00:00:00    1.91       8     910    1090
    ##  8 mist…       8 May    2014 2014-05-28 00:00:00    3.7       16    3580    4310
    ##  9 mist…       9 June   2014 2014-06-05 00:00:00    2.52      14    2400    2790
    ## 10 mist…      10 June   2014 2014-06-11 00:00:00    3.76      18    1340    1730
    ## # … with 631 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​dumpster, ²​weight_tons, ³​volume_cubic_yards, ⁴​plastic_bottles,
    ## #   ⁵​polystyrene

There are **15 columns** and **641 rows** in this combined dataset.

Key variables of interest include the specific trash wheel, either
`mister` or `doctor`, `weight_tons`, and quantities of commonly
collected items, including `cigarette_butts`, `chip_bags`, and other
similar items. It is worth noting that `sports_balls` are collected (or
recorded) by Mr. Trash Wheel but not by Professor Trash Wheel.

-   The total weight of trash collected by Professor Trash Wheel was
    **190.12 tons**.

-   The total number of sports balls collected by Mr. Trash Wheel in
    2020 was **856**.

# Problem 3

*Importing pols_data.csv and cleaning it.*

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 january        23      51     253      23      45     198 dem      
    ##  2  1947 february       23      51     253      23      45     198 dem      
    ##  3  1947 march          23      51     253      23      45     198 dem      
    ##  4  1947 april          23      51     253      23      45     198 dem      
    ##  5  1947 may            23      51     253      23      45     198 dem      
    ##  6  1947 june           23      51     253      23      45     198 dem      
    ##  7  1947 july           23      51     253      23      45     198 dem      
    ##  8  1947 august         23      51     253      23      45     198 dem      
    ##  9  1947 september      23      51     253      23      45     198 dem      
    ## 10  1947 october        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

*Importing snp.csv and cleaning it.*

    ## # A tibble: 787 × 4
    ##     year month      day close
    ##    <dbl> <chr>    <int> <dbl>
    ##  1  2015 july         1 2080.
    ##  2  2015 june         1 2063.
    ##  3  2015 may          1 2107.
    ##  4  2015 april        1 2086.
    ##  5  2015 march        2 2068.
    ##  6  2015 february     2 2104.
    ##  7  2015 january      2 1995.
    ##  8  2014 december     1 2059.
    ##  9  2014 november     3 2068.
    ## 10  2014 october      1 2018.
    ## # … with 777 more rows

*Now importing and cleaning unemployment.csv*

    ## # A tibble: 816 × 3
    ##     year month     unemployment_rate
    ##    <dbl> <chr>                 <dbl>
    ##  1  1948 january                 3.4
    ##  2  1948 february                3.8
    ##  3  1948 march                   4  
    ##  4  1948 april                   3.9
    ##  5  1948 may                     3.5
    ##  6  1948 june                    3.6
    ##  7  1948 july                    3.6
    ##  8  1948 august                  3.9
    ##  9  1948 september               3.8
    ## 10  1948 october                 3.7
    ## # … with 806 more rows

*Merging snp into pols to create a new dataframe, pols_and_snp.*

    ## # A tibble: 9,438 × 12
    ##     year month.x gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ month.y
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <chr>  
    ##  1  1947 january      23      51     253      23      45     198 dem     <NA>   
    ##  2  1947 februa…      23      51     253      23      45     198 dem     <NA>   
    ##  3  1947 march        23      51     253      23      45     198 dem     <NA>   
    ##  4  1947 april        23      51     253      23      45     198 dem     <NA>   
    ##  5  1947 may          23      51     253      23      45     198 dem     <NA>   
    ##  6  1947 june         23      51     253      23      45     198 dem     <NA>   
    ##  7  1947 july         23      51     253      23      45     198 dem     <NA>   
    ##  8  1947 august       23      51     253      23      45     198 dem     <NA>   
    ##  9  1947 septem…      23      51     253      23      45     198 dem     <NA>   
    ## 10  1947 october      23      51     253      23      45     198 dem     <NA>   
    ## # … with 9,428 more rows, 2 more variables: day <int>, close <dbl>, and
    ## #   abbreviated variable name ¹​president

*Merging unemployment in the result of merging snp into pols to create a
large and final dataframe, economic_data.*

    ## # A tibble: 113,124 × 14
    ##     year month.x gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ month.y
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <chr>  
    ##  1  1947 january      23      51     253      23      45     198 dem     <NA>   
    ##  2  1947 februa…      23      51     253      23      45     198 dem     <NA>   
    ##  3  1947 march        23      51     253      23      45     198 dem     <NA>   
    ##  4  1947 april        23      51     253      23      45     198 dem     <NA>   
    ##  5  1947 may          23      51     253      23      45     198 dem     <NA>   
    ##  6  1947 june         23      51     253      23      45     198 dem     <NA>   
    ##  7  1947 july         23      51     253      23      45     198 dem     <NA>   
    ##  8  1947 august       23      51     253      23      45     198 dem     <NA>   
    ##  9  1947 septem…      23      51     253      23      45     198 dem     <NA>   
    ## 10  1947 october      23      51     253      23      45     198 dem     <NA>   
    ## # … with 113,114 more rows, 4 more variables: day <int>, close <dbl>,
    ## #   month <chr>, unemployment_rate <dbl>, and abbreviated variable name
    ## #   ¹​president

These datasets contained information related to various aspects of the
economy over a wide variety of years. The first, pols_data, included
political data (elected president’s party, for instance) by year and
month. The second, snp_data, included data related to stock market total
values by year and month. The third, unemployment_data, included data
related to the unemployment rate by year and month.

The final joined complete dataset contains **113124** rows and **14**
columns. Key variables include those collated from the individual
datasets, such that a stock market value on a given date can be observed
along with the elected representative’s political party, unemployment
rates at the time, and others. The data ranges from years **1947 -
2015**.
